KiranKhadd29/practiceFlutter

- Sayali Workspace/demoproject/lib/main.dart
> Text & widgets & it's style

- Kiran Workspace/flutter_basics/lib/main.dart
> Widgets - ListView, ListView Builder, ListView Seperated & ListTile

- Sayali Workspace/demoproject/lib/main.dart
> Container Decoration

- Sayali Workspace/demoproject/lib/main.dart
> Expanded widget for Row and column

- Sayali Workspace/demoproject/lib/main.dart
> Margin and Padding

- Sayali Workspace/demoproject/lib/main.dart
- Sayali Workspace/demoproject/lib/ui_helper/util.dart
> Style and themes

- Sayali Workspace/demoproject/lib/main.dart
> Card Widget

- Sayali Workspace/demoproject/lib/main.dart
> Get current date and time

- Sayali Workspace/demoproject/lib/main.dart
- Sayali Workspace/demoproject/pubspec.lock
- Sayali Workspace/demoproject/pubspec.yaml
> Date format

- Sayali Workspace/demoproject/lib/main.dart
> Date and Time picker

- Sayali Workspace/demoproject/lib/main.dart
> Adding text input widgets

- Sayali Workspace/demoproject/lib/main.dart
> Grid View .count and .extent

- Sayali Workspace/demoproject/lib/main.dart
> Grid View .builder for dynamic values

- Sayali Workspace/demoproject/lib/main.dart
> Call back function

- Sayali Workspace/demoproject/lib/main.dart
- Sayali Workspace/demoproject/lib/widgets/rounded_btn.dart
> Custom widgets

- Sayali Workspace/demoproject/lib/main.dart
> Splitting into widgets

- Sayali Workspace/demoproject/lib/main.dart
> Stack widget

- Sayali Workspace/demoproject/lib/main.dart
> Icon widget

- Sayali Workspace/demoproject/lib/main.dart
- Sayali Workspace/demoproject/pubspec.lock
- Sayali Workspace/demoproject/pubspec.yaml
> Font awesome icon

- Sayali Workspace/demoproject/lib/main.dart
> Wrap widget

- Sayali Workspace/demoproject/lib/main.dart
> statefull widgets

- Sayali Workspace/demoproject/lib/main.dart
> Basic calculator

- Sayali Workspace/demoproject/lib/IntroPage.dart
- Sayali Workspace/demoproject/lib/main.dart
> Switching from one screen to another

- Sayali Workspace/demoproject/lib/SplashScreen.dart
- Sayali Workspace/demoproject/lib/main.dart
> Splash screen

- Sayali Workspace/demoproject/lib/ProfileScreen.dart
- Sayali Workspace/demoproject/lib/main.dart
> Passing data from one screen to another
